# Generated by Django 6.0.3 on 2026-07-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_status',
            field=models.CharField(choices=[('open_to_work', 'Open to Work'), ('employed', 'Currently Working'), ('freelancing', 'Available for Freelance')], default='open_to_work', max_length=20),
        ),
    ]
