# Generated by Django 6.0.3 on 2026-07-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume (PDF recommended)', null=True, upload_to='resumes/'),
        ),
    ]
