# Generated by Django 6.0.1 on 2026-08-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload your profile photo', null=True, upload_to='profile/'),
        ),
    ]
